server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 52.79.225.4
  client:
    serviceUrl:
      defaultZone: http://13.209.209.29:8761/eureka/

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key

spring:
  application:
    name: msa-api-gateway
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    msa-community-service:
      path: /community/**
      stripPrefix: false
    msa-legacy-service:
      path: /**
  sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000